name: API Client publish

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@oacore/api-client'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
