name: Pull request check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      -
        name: Checkout the branch
        uses: actions/checkout@v1
      -
        name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        name: Install dependencies
        run: npm ci
      -
        name: Check project builds
        run: npm run build
      -
        name: Check code quality
        run: npm run lint
      -
        name: Run tests
        run: npm test
