name: Pull request check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      -
        uses: actions/checkout@v1
      -
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        name: install packages
        run: npm ci
      -
        name: build
        run: npm run build
      -
        name: lint
        run: npm run lint
      -
        name: test
        run: npm test
